-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;
USE ecommerce_db;

-- DROP TABLE IF EXISTS category, product, product_tag, tag;

CREATE TABLE category (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(30) NOT NULL
);

CREATE TABLE product (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(30) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  stock INTEGER NOT NULL DEFAULT 10,
  category_id INTEGER,
  CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE SET NULL
);

CREATE TABLE tag (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  tag_name VARCHAR(30)
);

CREATE TABLE product_tag (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  product_id INTEGER,
  CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE SET NULL,
  tag_id INTEGER,
  CONSTRAINT fk_tag FOREIGN KEY (tag_id) REFERENCES tag(id) ON DELETE SET NULL
);

